#!/usr/bin/env ruby
require 'shellwords'

def sh(command)
  system command
  exit $?.exitstatus if $?.exitstatus != 0
end

class String
  
  def esc
    Shellwords.shellescape(self)
  end
  
  def nil_if_empty
    nil if empty?
  end
  
end

class Array
  
  def esc
    self.map(&:esc).join(" ")
  end
  
end

PROGRAM = File.basename $0

HELP = <<HELP

Usage: #{PROGRAM} [-h|--help] branch

Removes branch locally and remotely.

If "-h" or "--help" is specified then this program prints this message and
exits.

HELP

# Parse args.
if ARGV[0] == "-h" or ARGV[0] == "--help"
  print HELP
  exit
end
branch = ARGV[0] or abort "#{PROGRAM}: branch to remove is not specified"
# Close the current branch!
current_branch_remote =
  `git config --get branch.#{current_branch.esc}.remote`.strip.nil_if_empty
sh "git branch -D #{current_branch.esc}"
if current_branch_remote then
  sh "git push #{current_branch_remote} :#{current_branch.esc}"
end
