#!/bin/bash

PROGRAM="`basename "$0"`"

function log_run()
{
  echo "$PROGRAM:" "$@" >&2
  "$@"
}

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  cat <<HELP

Usage: $PROGRAM [-h|--help]

Synchronizes "master" branch, its remote counterpart and SVN trunk
from svn-remote "svn". All remote changes are merged using
"git rebase --preserve-merges".

If "-h" or "--help" is specified then this program prints this message and
exits.

HELP
  exit
fi

current_branch=`git symbolic-ref --short HEAD`
{ [ "$current_branch" = "master" ] || log_run git checkout master; } && \
log_run git pull --rebase=preserve && \
log_run git update-ref \
  "`git config svn-remote.svn.fetch | cut -d ':' -f 2`" \
  "`git log --grep=^git-svn-id: --first-parent -1 --format=%H`" && \
log_run git svn rebase --preserve-merges && \
log_run git svn dcommit && \
log_run git push `git config branch.master.remote` master && \
{ [ "$current_branch" = "master" ] || log_run git checkout "$current_branch"; }
