#!/bin/bash

function usage() {
  cat <<USAGE
    
Usage: $(basename "$0") [options] branch-base-name

Creates new branch and checks it out. The new branch name is chosen according to
the following rules: 1) if the current branch is "master" then
the new branch is "branch-base-name"; 2) otherwise the new branch is
"<current-branch-name>.d/<branch-base-name>".

Options:
  -h, --help     Print this message and exit.

USAGE
}

# Parse args.
if [ "$1" == "-h" -o "$1" == "--help" -o "$1" == "" ]; then usage; exit; fi
branch_base_name="$1"
# Do the job.
current_branch="$(git symbolic-ref --short HEAD)" && \
{
  if [ "$current_branch" == "master" ]; then
    git checkout -b "$branch_base_name"
  else
    git checkout -b "$current_branch.d/$branch_base_name"
  fi
}
