#!/usr/bin/env ruby
require 'shellwords'

def sh(command)
  system command
  exit $?.exitstatus if $?.exitstatus != 0
end

class String
  
  def esc
    Shellwords.shellescape(self)
  end
  
  def nil_if_empty
    nil if empty?
  end
  
end

class Array
  
  def esc
    self.map(&:esc).join(" ")
  end
  
end

PROGRAM = File.basename $0

HELP = <<HELP

Usage: #{PROGRAM} [-h|--help] [merge-options] [--] upstream-branch

Merges current branch into upstream-branch and deletes the current branch
locally and remotely.

HELP

# Parse args.
if ARGV[0] == "-h" or ARGV[0] == "--help"
  print HELP
  exit
end
dest_branch = ARGV.pop
ARGV.pop if ARGV.last == "--"
merge_opts = ARGV
# Close the current branch!
current_branch = `git symbolic-ref --short HEAD`.strip
current_branch_remote =
  `git config --get branch.#{current_branch.esc}.remote`.strip.nil_if_empty
sh "git checkout -- #{dest_branch.esc}"
sh "git merge #{merge_opts.esc} -- #{current_branch.esc}"
sh "git branch -D -- #{current_branch.esc}"
if current_branch_remote then
  sh "git push -- #{current_branch_remote} :#{current_branch.esc}"
end
