#!/bin/bash

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  cat <<HELP

Usage: `basename $0` [-h|--help]

Synchronizes "master" branch, its upstream counterpart and SVN trunk.

If "-h" or "--help" is specified then this program prints this message and
exits.

HELP
  exit
fi

current_branch=`git symbolic-ref --short HEAD`
{ [ "$current_branch" = "master" ] || git checkout master; } && \
git pull && \
git svn rebase && \
git svn dcommit && \
git push `git config branch.master.remote` master && \
{ [ "$current_branch" = "master" ] || git checkout "$current_branch"; }
